/**
 * 共享契约包导出入口。
 *
 * 集中公开 API 与移动端共同使用的 Zod schema 和推断类型，避免消费者绕过权威契约路径。
 *
 * Responsibilities:
 * - 导出 HelloWorld、知识库与音频工作区网络契约。
 *
 * Notes:
 * - 不包含传输实现或应用业务逻辑。
 */
export { HelloResponseSchema, type HelloResponse } from './hello.ts';
export {
  ApiErrorCodeSchema,
  ApiErrorResponseSchema,
  EntityIdSchema,
  type ApiErrorCode,
  type ApiErrorResponse,
} from './common.ts';
export {
  DocumentChunkListResponseSchema,
  DocumentChunkSchema,
  DocumentFormatSchema,
  DocumentStatusSchema,
  DocumentUploadResponseSchema,
  KnowledgeDocumentDetailSchema,
  KnowledgeDocumentListResponseSchema,
  KnowledgeDocumentSchema,
  MarkdownLocatorSchema,
  SourceLocatorSchema,
  SpreadsheetLocatorSchema,
  WordLocatorSchema,
  type DocumentChunk,
  type DocumentFormat,
  type DocumentStatus,
  type DocumentUploadResponse,
  type KnowledgeDocument,
  type KnowledgeDocumentDetail,
  type SourceLocator,
} from './document.ts';
export {
  KnowledgeBaseCreateRequestSchema,
  KnowledgeBaseDetailSchema,
  KnowledgeBaseGroupLinkRequestSchema,
  KnowledgeBaseListResponseSchema,
  KnowledgeBaseSettingsSchema,
  KnowledgeBaseSummarySchema,
  KnowledgeBaseUpdateRequestSchema,
  type KnowledgeBaseCreateRequest,
  type KnowledgeBaseDetail,
  type KnowledgeBaseGroupLinkRequest,
  type KnowledgeBaseSettings,
  type KnowledgeBaseSummary,
} from './knowledgeBase.ts';
export {
  RagCitationSchema,
  RagHistoryItemSchema,
  RagHistoryResponseSchema,
  RagQueryRequestSchema,
  RagQueryResponseSchema,
  RagUsageSchema,
  type RagHistoryItem,
  type RagHistoryResponse,
  type RagQueryRequest,
  type RagQueryResponse,
} from './rag.ts';
export {
  DEFAULT_GROUP_ANALYSIS_FOCUS,
  DEFAULT_GROUP_ANALYSIS_TONE,
  GroupAnalysisSettingsSchema,
  GroupAnalysisTimingSchema,
  GroupCreateRequestSchema,
  GroupDetailSchema,
  GroupListResponseSchema,
  GroupMetricsSchema,
  GroupSummarySchema,
  GroupResourceLinksUpdateRequestSchema,
  GroupSettingsSchema,
  GroupSettingsUpdateRequestSchema,
  type GroupAnalysisSettings,
  type GroupAnalysisTiming,
  type GroupCreateRequest,
  type GroupMetrics,
  type GroupResourceLinksUpdateRequest,
  type GroupSettings,
  type GroupSettingsUpdateRequest,
  type GroupSummary,
} from './group.ts';
export {
  AudioFailureStageSchema,
  AudioFailureDiagnosticCategorySchema,
  AudioFailureDetailsSchema,
  AudioFailureIssueSchema,
  AudioTranscriptionActivitySchema,
  AudioTranscriptionStageSchema,
  AudioFileListResponseSchema,
  AudioFileSummarySchema,
  AudioProcessingStatusSchema,
  AUDIO_TRANSCRIPTION_MODELS,
  AUDIO_TRANSCRIPTION_MODEL_CAPABILITIES,
  DEFAULT_AUDIO_TRANSCRIPTION_MODEL,
  QWEN_AUDIO_FILETRANS_MODEL,
  AudioTranscriptionCapabilitiesResponseSchema,
  AudioTranscriptionDiarizationAvailabilitySchema,
  AudioTranscriptionPriceSchema,
  AudioTranscriptionPriceUnitSchema,
  AudioTranscriptionPricingSchema,
  AudioTranscriptionPreprocessingSchema,
  AudioTranscriptionProviderSchema,
  AudioTranscriptionSegmentationModeSchema,
  AudioTranscriptionSpeakerIdentityScopeSchema,
  AudioTranscriptionModelSchema,
  AudioTranscriptionModelCapabilitySchema,
  AudioTranscriptionResponseGranularitySchema,
  AudioTranscriptionTimestampAvailabilitySchema,
  AudioTranscriptionTimestampGranularitySchema,
  AudioTranscriptionStartRequestSchema,
  AudioTranscriptionStartResponseSchema,
  type AudioFailureStage,
  type AudioFailureDiagnosticCategory,
  type AudioFailureDetails,
  type AudioFailureIssue,
  type AudioTranscriptionActivity,
  type AudioTranscriptionStage,
  type AudioFileSummary,
  type AudioProcessingStatus,
  type AudioTranscriptionCapabilitiesResponse,
  type AudioTranscriptionDiarizationAvailability,
  type AudioTranscriptionPrice,
  type AudioTranscriptionPriceUnit,
  type AudioTranscriptionPricing,
  type AudioTranscriptionPreprocessing,
  type AudioTranscriptionProvider,
  type AudioTranscriptionSegmentationMode,
  type AudioTranscriptionSpeakerIdentityScope,
  type AudioTranscriptionModel,
  type AudioTranscriptionModelCapability,
  type AudioTranscriptionResponseGranularity,
  type AudioTranscriptionTimestampAvailability,
  type AudioTranscriptionTimestampGranularity,
  type AudioTranscriptionStartRequest,
  type AudioTranscriptionStartResponse,
} from './audio.ts';
export {
  CORE_BUSINESS_ROLES,
  CustomBusinessRolesSchema,
  DataSourceAnalysisSettingsSchema,
  DataSourceAudioUploadResponseSchema,
  DataSourceConnectionStatusSchema,
  DataSourceCreateRequestSchema,
  DataSourceDetailSchema,
  DataSourceGroupLinkRequestSchema,
  DataSourceIngestionListResponseSchema,
  DataSourceIngestionRecordSchema,
  DataSourceListResponseSchema,
  DataSourceLocationSchema,
  DataSourceMetricsSchema,
  DataSourceSummarySchema,
  DataSourceTypeSchema,
  DataSourceUpdateRequestSchema,
  LinkedDataSourceGroupListResponseSchema,
  LinkedDataSourceGroupSchema,
  type DataSourceAudioUploadResponse,
  type DataSourceCreateRequest,
  type DataSourceDetail,
  type DataSourceGroupLinkRequest,
  type DataSourceIngestionRecord,
  type DataSourceSummary,
  type DataSourceUpdateRequest,
  type LinkedDataSourceGroup,
} from './dataSource.ts';
export {
  AudioBusinessAnalysisStartRequestSchema,
  AudioBusinessAnalysisStartResponseSchema,
  AudioBusinessAnalysisStateSchema,
  AudioEmotionArousalSchema,
  AudioEmotionAttitudeSchema,
  AudioEmotionLabelSchema,
  AudioEmotionPaceSchema,
  AudioEmotionPausePatternSchema,
  AudioEmotionPitchVariationSchema,
  AudioEmotionVolumeTrendSchema,
  AudioPostAnalysisStartResponseSchema,
  AudioPostAnalysisStateSchema,
  AudioPostAnalysisTypeSchema,
  AudioTranscriptConfirmationRequestSchema,
  AudioTranscriptConfirmationResponseSchema,
  AudioTranscriptConfirmationSegmentInputSchema,
  AudioTranscriptConfirmationStateSchema,
  BusinessRoleKindSchema,
  BusinessAnalysisCitationSchema,
  BusinessAnalysisResultSchema,
  BusinessAnalysisTagCategorySchema,
  BusinessAnalysisTagSchema,
  AnalysisInvalidSegmentSchema,
  AnalysisSceneSchema,
  AnalysisSummarySectionSchema,
  AudioAnalysisDetailSchema,
  AudioTranscriptionDiarizationStatusSchema,
  AudioTranscriptionMetadataSchema,
  SegmentAiTagSchema,
  SpeakerReviewFindingSchema,
  SpeakerReviewResolutionResponseSchema,
  SpeakerReviewSchema,
  SegmentEmotionAnalysisSchema,
  SegmentRoleAnalysisSchema,
  TranscriptSegmentSchema,
  TranscriptWordSchema,
  type AnalysisInvalidSegment,
  type AnalysisScene,
  type AnalysisSummarySection,
  type AudioAnalysisDetail,
  type AudioBusinessAnalysisStartRequest,
  type AudioBusinessAnalysisStartResponse,
  type AudioBusinessAnalysisState,
  type AudioEmotionLabel,
  type AudioPostAnalysisStartResponse,
  type AudioPostAnalysisState,
  type AudioPostAnalysisType,
  type AudioTranscriptConfirmationRequest,
  type AudioTranscriptConfirmationResponse,
  type AudioTranscriptConfirmationState,
  type BusinessRoleKind,
  type BusinessAnalysisCitation,
  type BusinessAnalysisResult,
  type BusinessAnalysisTag,
  type BusinessAnalysisTagCategory,
  type AudioTranscriptionDiarizationStatus,
  type AudioTranscriptionMetadata,
  type SegmentAiTag,
  type SpeakerReview,
  type SpeakerReviewFinding,
  type SpeakerReviewResolutionResponse,
  type SegmentEmotionAnalysis,
  type SegmentRoleAnalysis,
  type TranscriptSegment,
  type TranscriptWord,
} from './analysis.ts';
export {
  AudioAnalysisStatusStreamEventSchema,
  AudioBusinessAnalysisLiveStateSchema,
  DataSourceAudioStreamEventSchema,
  KnowledgeDocumentStreamEventSchema,
  type AudioAnalysisStatusStreamEvent,
  type DataSourceAudioStreamEvent,
  type KnowledgeDocumentStreamEvent,
} from './liveUpdates.ts';
export {
  AudioAiExecutionKindSchema,
  AudioAiExecutionModelCallSchema,
  AudioAiExecutionRunSchema,
  AudioAiExecutionStatusSchema,
  AudioAiExecutionStepSchema,
  AudioAiExecutionStreamEventSchema,
  AudioAiExecutionToolCallSchema,
  AudioAiExecutionTraceResponseSchema,
  AudioAiKnowledgeBaseSnapshotSchema,
  AudioAiRetrievalHitSchema,
  type AudioAiExecutionKind,
  type AudioAiExecutionRun,
  type AudioAiExecutionStatus,
  type AudioAiExecutionStreamEvent,
  type AudioAiExecutionTraceResponse,
} from './aiExecution.ts';
export {
  AdminSessionResponseSchema,
  AiCapabilitySchema,
  AliyunOssConnectionConfigSchema,
  AliyunOssCredentialInputSchema,
  CapabilityBindingSchema,
  CapabilityBindingWriteSchema,
  CredentialBundleInputSchema,
  CredentialDescriptorSchema,
  CredentialSourceSchema,
  DashScopeConnectionConfigSchema,
  DashScopeCredentialInputSchema,
  DeepSeekConnectionConfigSchema,
  DeepSeekCredentialInputSchema,
  LegacyConfigurationStatusSchema,
  LocalCredentialDescriptorSchema,
  LocalCredentialProviderStatusSchema,
  ProviderConnectionConfigSchema,
  ProviderConnectionSchema,
  ProviderConnectionWriteSchema,
  ProviderTypeSchema,
  SettingsOverviewSchema,
  TransportSecurityModeSchema,
  TransportSecuritySchema,
  type AiCapability,
  type CapabilityBinding,
  type CapabilityBindingWrite,
  type CredentialBundleInput,
  type CredentialSource,
  type LocalCredentialProviderStatus,
  type ProviderConnection,
  type ProviderConnectionWrite,
  type ProviderType,
  type SettingsOverview,
  type TransportSecurityMode,
} from './settings.ts';
